# Generated by Django 5.1 on 2024-08-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_student_grade_student_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='students',
            new_name='student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.parent'),
        ),
    ]
